# DO NOT CHANGE THE CODE BELOW
before_install:
  - R -q -e 'if (!requireNamespace("remotes", quietly = TRUE)) install.packages("remotes")'
  - R -q -e 'if (!requireNamespace("curl", quietly = TRUE)) install.packages("curl")'
  - R -q -e 'remotes::install_github("ropenscilabs/tic"); tic::prepare_all_stages(); tic::before_install()'
install: R -q -e 'tic::install()'
after_install: 
  - R -q -e 'tic::after_install()'
before_script:
  - sudo apt-get update
  - sudo apt-get install python3 python3-pip
  - pip3 install --upgrade --ignore-installed --user travis virtualenv
  - R CMD INSTALL .
  - R -e 'keras::install_keras(tensorflow = Sys.getenv("TENSORFLOW_VERSION"), extra_packages = "IPython")'
  - R -e 'tensorflow::tf_config()'
  - R -e 'keras::install_keras(extra_packages = c("tensorflow-hub", "tabnet>=0.1.4.1")'
  - R -q -e 'tic::before_script()'
script: R -q -e 'tic::script()'
after_success: R -q -e 'tic::after_success()'
after_failure:
  - Rscript -e 'library(keras); testthat::test_dir("tests/testthat/")'
  - R -q -e 'tic::after_failure()'
before_deploy: R -q -e 'tic::before_deploy()'
deploy:
  provider: script
  script: R -q -e 'tic::deploy()'
  on:
    all_branches: true
after_deploy: R -q -e 'tic::after_deploy()'
after_script: R -q -e 'tic::after_script()'
# DO NOT CHANGE THE CODE ABOVE


# Custom parts:

# Header
language: r
sudo: false
dist: xenial
cache:
  packages: true
  directories:
    - $HOME/.keras
    - $HOME/.cache/pip
latex: true
pandoc_version: 2.5

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"
  - BUILD_PKGDOWN=true
  - _R_CHECK_TESTS_NLINES_=0
  - KERAS_BACKEND="tensorflow"
  - KERAS_IMPLEMENTATION="tensorflow"
  - TENSORFLOW_VERSION="default"
